### ISSUE TITLE
Support for multi module library

### ISSUE THREAD

**Issue by mscud** [tinesoft/generator-ngx-library#152]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X ] feature request
```
I am currently trying to get rid of a big library module and split the library into multiple modules, which is kind of recommended (i.e. that's what angular material does).
Unfortunately i get an error that my modules do not have the NgModule annotation.

```
ERROR in Error: Unexpected value 'AModule in [...]git/multi-module/demo/node_modules/multi-module/multi-module.d.ts' imported by the module 'HomeModule in [...]git/multi-module/demo/src/app/home/home.module.ts'. Please add a @NgModule annotation.
```

if i check the generated dist folder, in some files it seems to be ok (i.e. in multi-module.js), but not in the typings which then causes the error.

i created a sample demo project here:

https://github.com/mscud/multi-module

steps to reproduce:

```
npm start
npm run demo
```

Am i doing something wrong or do you have any suggestions how to solve this?

Thanks a lot and best regards,
Matthias

**Comment by faiztherocker** [comment]
I am facing the same issue. Contributors please let us know the solutions ASAP.
Also, let me know how to use scoped packages.
The library isn't configurable for scoped packages development.

**Comment by tinesoft** [comment]
Hello @mscud 

Thanks for filing the issue. I noticed in your `.yo-rc.json` that your are using an old version of the generator (`v4.5.1`)... Could you first update to latest `v5.7.1` and tell me if the issue still persists?


Cheers

**Comment by mscud** [comment]
@tinesoft: unfortunately i get the same error with the newest version:

https://github.com/mscud/multi-module-ngx-5

@faiztherocker: scoped libraries work, see #100 and #133

**Comment by tinesoft** [comment]
Ok @mscud and al.

I finally had a little time to investigate your issue, here are the result:

* Multi-module already works with the generator 👍   (no change required from me :blush: )
* Angular components, filters, pipes ... **need to be in `exports` array of their `NgModule`** (not just in `declarations`array)
* **Avoid using `barrels`**. So instead of: `~~export { MyModule } from './a'~~`, Use: `export { MyModule } from './a/a.module'` or `export { MyModule } from './a/index'`
* Prefer **explicit exports**. So Instead of:  `~~export { * } from ...~~`, Use: `export { MyModule } from ...` 

You can have a look at excellent [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap) for more details on how to properly organize your multi-module project.

I submitted a working [PR](https://github.com/mscud/multi-module-ngx-5/pull/1) to your https://github.com/mscud/multi-module-ngx-5 (fully updated the project to `v5.7.1` of generator-ngx-library, reorganized the modules in `src/`, fixed some tests)

![image](https://user-images.githubusercontent.com/4053092/38329205-63f0efd8-384d-11e8-89c8-3d70bcd54d5b.png)

You can just merge the PR and continue your hacking with the generator! 


I will create a new recipe in the docs section, to help others.


Cheers!

**Comment by mscud** [comment]
works fine! :)

thanks a lot and sorry for the late reply ;)
