### ISSUE TITLE
publishConfig is not preserved when building dist/

### ISSUE THREAD

**Issue by eh-am** [tinesoft/generator-ngx-library#159]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Generator Version
5.8.0

### Repro steps.

Add 
```js
"publishConfig": {
    "registry": "xx"
  },
```
to package.json in root

Then run `gulp build`

### Desired functionality.

I would expect to see the `publishConfig` object in `dist/package.json`

### Mention any other details that might be useful.

It seems easy to fix, just add
`publishConfig`
to
```js
let fieldsToCopy = ['version', 'description', 'keywords', 'author', 'repository', 'license', 'bugs', 'homepage'];
```
`(gulpfile.js, line 316)`

**Comment by tinesoft** [comment]
hi @eh-am 

Sorry for the late answer (actually, i responded via mail, but somehow it got lost).

In order to keep the distributed `package.json` as  light as possible, i only copy relevant  properties **required to publish** your package on NPM and **needed by final users** when installing it. 

`publishConfig` seems not to be in such case, but instead is very specific to your project.

You can simply edit the `gulpfile.js` as you did.
