### ISSUE TITLE
Avoid warning `requires a peer of @angular/core^4.0.0` ...

### ISSUE THREAD

**Issue by mlc-mlapis** [tinesoft/generator-ngx-library#2]
When testing version 2.0.1 and to avoid:
```
[11:34:24] Starting 'link'...
npm WARN mlc-test-library@0.0.1 requires a peer of @angular/core@^4.0.0 but none was installed.
npm WARN mlc-test-library@0.0.1 requires a peer of @angular/common@^4.0.0 but none was installed.
```
shouldn't be:
```
"dependencies": {
    "@angular/core": "^4.0.0",
    "@angular/common": "^4.0.0"
   },
"peerDependencies": {
    "@angular/core": "^4.0.0",
    "@angular/common": "^4.0.0"
   },
```

**Comment by tinesoft** [comment]
Hi again @mlc-mlapis,

The warnings that appear during the `linking` phase (which is required only once during development) can just be ignored.

In fact, the `package.json` in the linked folder (`dist/`) declares your library's dependencies as `peerDependencies` (and not `dependencies`), so that end users can specify exactly which version of the dependent packages they want to use, without being tied to your library's ones. This is intended.

In practice, the end user's project will already declare Angular dependencies in its `dependencies` section of its `package.json`,  so it should be no warnings at all (provided those dependencies respect the range defined by the library ). See for example the built-in demo application.

Cheers!

**Comment by mlc-mlapis** [comment]
Yeah, that's clear. Thanks for your notes.
